config/routes.rb
Rails.application.routes.draw do
  resources :vehicles
  root 'vehicles#index'
  

end

app/models/station.rb
class Station < ActiveRecord::Base
  validates :station_id, uniqueness: true
end

app/models/travel_info.rb
class TravelInfo < ActiveRecord::Base
  belongs_to :vehicle
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  has_many :travel_infos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  
  def index
  	@vehicles = Vehicle.all
  end

  def show
  	@vehicle = Vehicle.find(params[:id])
  end

  def destroy

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TransportationBuddy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/vehicles/index.html.erb
<div class="container">
  <h2>Vehicles</h2>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Vehicle Number</th>
        <th>Vehicle ID</th>
      </tr>
    </thead>
    <tbody>
      <% @vehicles.each do |vehicle| %>
        <tr data-link="<%= vehicle_path(vehicle) %>">
          <td><%= vehicle.vehicle_number %></td>
          <td><%= vehicle.vehicle_id %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>


<script>

</script>

app/views/vehicles/show.html.erb
<head>
    <title>Simple Map</title>
    <meta name="viewport" content="initial-scale=1.0">
    <meta charset="utf-8">
    <style>
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #map {
        height: 100%;
      }
    </style>
  </head>
 <div id="map"></div>
    <script>
      var map;
      var myLatLng = {lat: <%= @vehicle.travel_infos.last.try(:lat) %>, lng: <%= @vehicle.travel_infos.last.try(:lng) %>};
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: myLatLng,
          zoom: 17
        });


      var marker = new google.maps.Marker({
    position: myLatLng,
    map: map,
    title: 'Hello World!'
  });
      }

    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=YOU_API_KEY&callback=initMap"
    async defer></script>
<div class="container">
  <h2>Vehicle Number <%= @vehicle.vehicle_number %> - Vehicle ID <%= @vehicle.vehicle_id %></h2>
   
</div>